# Generated by Django 4.2 on 2024-12-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID_USER', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('Username', models.CharField(help_text="Entrez votre nom d'utilisateur...", max_length=200)),
                ('Email', models.EmailField(help_text='Entrez votre Email   Ex: xxxx@gmail.com', max_length=50)),
                ('Password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('Role', models.CharField(blank=True, choices=[('a', 'Administrateur'), ('s', 'Secrétaire'), ('u', 'Utilisateur')], default='u', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ID_Profile', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Entrez votre prénom...', max_length=20)),
                ('Last_Name', models.CharField(help_text='Entrez votre nom...', max_length=20)),
                ('Bio', models.TextField(help_text='Entrez votre biographie', max_length=1000)),
                ('Date_Joined', models.DateTimeField(auto_now_add=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users_app.user')),
            ],
            options={
                'ordering': ['Last_Name', 'First_Name'],
            },
        ),
    ]
