# Generated by Django 4.2 on 2024-12-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ID_Country', models.IntegerField(primary_key=True, serialize=False)),
                ('Countryname', models.CharField(max_length=40, unique=True)),
                ('Code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='EconomicIndicatorClass',
            fields=[
                ('ID_class', models.AutoField(primary_key=True, serialize=False)),
                ('Class_name', models.CharField(max_length=30, unique=True, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator_List',
            fields=[
                ('ID_Indicator', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=2000)),
                ('Name_EconomicIndicator', models.CharField(max_length=25)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form_app.economicindicatorclass')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('ID_Indicator', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('GDP', models.DecimalField(decimal_places=3, max_digits=15)),
                ('Inflation_Rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Population', models.IntegerField()),
                ('Population_growth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Balance_com', models.DecimalField(decimal_places=4, max_digits=15)),
                ('IDE', models.DecimalField(decimal_places=3, max_digits=15)),
                ('GDP_growth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('GDP_per_capita', models.DecimalField(decimal_places=3, max_digits=15)),
                ('GNI', models.DecimalField(decimal_places=3, max_digits=15)),
                ('GNI_per_capita', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Life_exp', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Maternal_mortality_ratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Mortality_rate_infant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form_app.country')),
            ],
        ),
    ]
