# Generated by Django 4.2 on 2024-12-26 11:16

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ID_Report', models.UUIDField(primary_key=True, serialize=False)),
                ('Generated_At', models.DateTimeField(auto_now_add=True)),
                ('Report_File', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='lien'), upload_to='lien')),
                ('EconomicIndicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form_app.economicindicator')),
            ],
        ),
    ]
